# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84b5e20e75a426973bfe6842793115b7017849014fb903aec6fda9ff90461f1d1649aa4ff8e2ecc8d8c8c5725bc257d96a46af7db8649eb481bedbcb06c29313

test:
  secret_key_base: c236c8ddbc2a746b183462ac57bbc340689f93e743b088afaf0563d4ff37529e75d70f4134f41318634ab3d3d2bea8ca37d1d8ffebb71c9185b976c9fd82cc9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
